#!/bin/sh

source config/current-ip.sh

export KUBE_VERSION=v1.9.3
echo "KUBE_VERSION=$KUBE_VERSION"

export ETCD_VERSION=v3.3.2
echo "ETCD_VERSION=$ETCD_VERSION"

export KUBE_IP_RANGE=10.254.0.0/16
echo "$KUBE_IP_RANGE=$KUBE_IP_RANGE"

export KUBE_APISERVER_IP=$CURR_NODE_IP
echo "KUBE_APISERVER_IP=$KUBE_APISERVER_IP"

export KUBE_MASTER_IP=$CURR_NODE_IP
echo "KUBE_MASTER_IP=$KUBE_MASTER_IP"

export ETCD_ENDPOINTS=https://$CURR_NODE_IP:2379
echo "ETCD_ENDPOINTS=$ETCD_ENDPOINTS"
